### ISSUE TITLE
[Android] suppressVolumeIndicator consumes all key press events, not just volume keys

### ISSUE THREAD

**Issue by DoctorMcKay** [capacitor-community/volume-buttons#12]
**Describe the bug**
When `suppressVolumeIndicator` is set to true when calling watchVolume, all key press events are consumed instead of just volume keys. This means that, among other things, the back button does not function while volume keys are being watched.

**To Reproduce**
1. Call `watchVolume` with `suppressVolumeIndicator` set to true
2. Press the device's back button

**Expected behavior**
The back button should either go back in the history stack, or emit the `backButton` event in the @capacitor/app plugin

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - N/A

**Smartphone (please complete the following information):**
 - Device: Emulated Pixel 4 Pro API 33
 - OS: Android 13
 - Browser: Mozilla/5.0 (Linux; Android 13; sdk_gphone64_x86_64 Build/TE1A.220922.010; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36
 - Version: `"@capacitor/core": "^6.1.1"`, `"@capacitor-community/volume-buttons": "^6.0.0"`

**Additional context**
N/A

**Comment by ryaa** [comment]
@DoctorMcKay thank you for the issue. I confirm the problem and implemented the required fix (see https://github.com/capacitor-community/volume-buttons/pull/13). Can you please test it on your end and let me know your thoughts? Thank you

**Comment by DoctorMcKay** [comment]
> @DoctorMcKay thank you for the issue. I confirm the problem and implemented the required fix (see #13). Can you please test it on your end and let me know your thoughts? Thank you

:+1: Looks good, I tested it and it works. Thanks!

**Comment by ryaa** [comment]
The new version 6.0.1 with the required change has been released. For more details please see [CHANGELOG](https://github.com/capacitor-community/volume-buttons/blob/master/CHANGELOG.md)
